### ISSUE TITLE
動作検証

### ISSUE THREAD

**Issue by technicakidz** [gbybk945/streamlit#6]
### 概要
参考リポジトリをベースにカスタマイズしたり動作確認とコード理解を目的としている認識。
動作検証の進め方で詰まる部分があればこの issue のコメント欄で行う。

### 完了条件
- [x] ベースのコードが意図する動作がローカル環境で確認できる

**Comment by gbybk945** [comment]
・仮想環境下で各ライブラリ等をインストールしたところ、pipのバージョンが古いというＷＡＲＮＩＮＧコメントが発生した。
・DockerやGCPは実行していない。
・ローカル環境において問題なく実行できている。
